# Generated by Django 5.2.8 on 2025-11-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='slot',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
