# Generated by Django 5.2.8 on 2025-12-08 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapist', '0004_merge_20251126_2233'),
        ('therapy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('pain_change', models.CharField(blank=True, choices=[('better', 'Better'), ('same', 'Same'), ('worse', 'Worse')], max_length=20, null=True)),
                ('stress_change', models.CharField(blank=True, choices=[('better', 'Better'), ('same', 'Same'), ('worse', 'Worse')], max_length=20, null=True)),
                ('sleep_change', models.CharField(blank=True, choices=[('better', 'Better'), ('same', 'Same'), ('worse', 'Worse')], max_length=20, null=True)),
                ('communication_rating', models.IntegerField(default=5)),
                ('comfort_level', models.CharField(blank=True, choices=[('comfortable', 'Comfortable'), ('average', 'Average'), ('uncomfortable', 'Uncomfortable')], max_length=20, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapist.therapist')),
                ('therapy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapy.therapy')),
            ],
        ),
    ]
