# Generated by Django 5.2.8 on 2025-11-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_rename_date_of_birth_therapist_dob_and_more'),
        ('therapist', '0003_therapistprofile'),
    ]

    operations = [
    ]
