# Generated by Django 5.2.8 on 2025-12-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_merge_20251126_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='therapist',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='therapist.therapy'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapist.center'),
        ),
    ]
