# Generated by Django 5.2.8 on 2025-12-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_center_therapist_experience_therapist_expertise_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TherapistProfile',
        ),
    ]
