# Generated by Django 5.2.8 on 2025-12-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_delete_therapistprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='expertise',
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist')),
            ],
        ),
        migrations.AddField(
            model_name='therapist',
            name='expertise',
            field=models.TextField(blank=True, help_text='Enter expertise separated by commas'),
        ),
    ]
