# Generated by Django 5.2.8 on 2025-12-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0008_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('therapy_performed', models.CharField(max_length=150)),
                ('session_notes', models.TextField()),
                ('inventory_used', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='session_pdfs/')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='therapist.therapist')),
            ],
        ),
    ]
