# Generated by Django 5.2.8 on 2025-11-25 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_therapy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='therapist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapistprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
