# Generated by Django 5.2.8 on 2025-12-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='prakriti_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='therapy_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
