# Generated by Django 5.2.8 on 2025-12-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patientprofile_prakriti_type_patientprofile_symptoms_and_more'),
        ('therapist', '0004_merge_20251126_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='therapy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapist.therapy'),
        ),
    ]
