# Generated by Django 5.2.8 on 2025-12-08 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patientprofile_prakriti_type_patientprofile_symptoms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('therapy_name', models.CharField(max_length=255)),
                ('recommended_by', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(choices=[('detox', 'Detoxification'), ('pain', 'Pain relief'), ('stress', 'Stress reduction'), ('digestion', 'Improving digestion/metabolism'), ('other', 'Other')], default='detox', max_length=20)),
                ('purpose_other', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_explained', models.TextField()),
                ('expected_benefits', models.TextField(blank=True, null=True)),
                ('sessions', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_post_instructions', models.TextField(blank=True, null=True)),
                ('risks_and_side_effects', models.TextField(blank=True, null=True)),
                ('patient_responsibilities', models.TextField(blank=True, null=True)),
                ('confidentiality_ack', models.BooleanField(default=True)),
                ('right_to_withdraw_ack', models.BooleanField(default=True)),
                ('patient_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_signed_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('therapist_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('therapist_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
