# Generated by Django 5.2.8 on 2025-12-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_patientconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_name', models.CharField(max_length=100)),
                ('therapy_description', models.TextField()),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('understood_risks', models.BooleanField(default=False)),
                ('voluntary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='consent_pdfs/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patientprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientConsent',
        ),
    ]
