# Generated by Django 5.2.8 on 2025-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_consentform_delete_patientconsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentform',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='consentform',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='consentform',
            name='patient_name',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consentform',
            name='signature',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='understood_risks',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='voluntary',
            field=models.BooleanField(),
        ),
    ]
