# Generated by Django 5.2.8 on 2025-12-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_notificationapikey_appointment_status_and_more'),
        ('Patient', '0009_remove_consentform_patient_and_more'),
    ]

    operations = [
    ]
