# Generated by Django 5.2.8 on 2025-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('pre_care', models.TextField(blank=True, null=True)),
                ('post_care', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
