# Generated by Django 5.2.8 on 2025-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='description',
        ),
        migrations.AlterField(
            model_name='therapy',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
